from cassandra.cluster import Cluster


def cargar_datos_adquisiciones():
	#session.execute("DROP TABLE adquisiciones;")
	session.execute("CREATE TABLE adquisiciones (id_obj int PRIMARY KEY, producto text, importe float, periodo int);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (1,'producto_1',12.5,1);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (2,'producto_1',12.5,1);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (3,'producto_1',12.5,1);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (4,'producto_1',12.5,1);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (5,'producto_1',12.5,1);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (6,'producto_1',12.5,1);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (7,'producto_1',12.5,1);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (8,'producto_2',2.9,1);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (9,'producto_2',2.9,1);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (10,'producto_2',2.9,1);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (11,'producto_2',2.9,1);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (12,'producto_3',4.8,1);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (13,'producto_3',4.8,1);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (14,'producto_4',11.7,1);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (15,'producto_4',11.7,1);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (16,'producto_5',17.5,1);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (17,'producto_5',17.5,1);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (18,'producto_5',17.5,1);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (19,'producto_5',17.5,1);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (20,'producto_1',12.7,2);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (21,'producto_1',12.7,2);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (22,'producto_1',12.7,2);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (23,'producto_1',12.7,2);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (24,'producto_1',12.7,2);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (25,'producto_1',12.7,2);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (26,'producto_1',12.7,2);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (27,'producto_2',2.7,2);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (28,'producto_2',2.7,2);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (29,'producto_2',2.7,2);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (30,'producto_2',2.7,2);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (31,'producto_5',17.4,2);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (32,'producto_5',17.4,2);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (33,'producto_5',17.4,2);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (34,'producto_5',17.4,2);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (35,'producto_4',11.9,2);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (36,'producto_4',11.9,2);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (37,'producto_3',4.4,2);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (38,'producto_3',4.4,2);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (39,'producto_1',13.1,3);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (40,'producto_1',13.1,3);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (41,'producto_1',13.1,3);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (42,'producto_2',3.1,3);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (43,'producto_2',3.1,3);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (44,'producto_2',3.1,3);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (45,'producto_3',4.3,3);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (46,'producto_3',4.3,3);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (47,'producto_3',4.3,3);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (48,'producto_3',4.3,3);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (49,'producto_3',4.3,3);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (50,'producto_4',11.9,3);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (51,'producto_5',17.4,3);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (52,'producto_5',17.4,3);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (53,'producto_5',17.4,3);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (54,'producto_5',17.4,3);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (55,'producto_1',12.9,4);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (56,'producto_1',12.9,4);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (57,'producto_1',12.9,4);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (58,'producto_1',12.9,4);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (59,'producto_1',12.9,4);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (60,'producto_1',12.9,4);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (61,'producto_2',2.5,4);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (62,'producto_2',2.5,4);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (63,'producto_2',2.5,4);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (64,'producto_3',4.3,4);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (65,'producto_3',4.3,4);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (66,'producto_3',4.3,4);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (67,'producto_3',4.3,4);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (68,'producto_4',11.8,4);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (69,'producto_4',11.8,4);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (70,'producto_5',17.6,4);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (71,'producto_5',17.6,4);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (72,'producto_5',17.6,4);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (73,'producto_5',17.6,4);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (74,'producto_5',17.6,4);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (75,'producto_1',13.2,5);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (76,'producto_1',13.2,5);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (77,'producto_1',13.2,5);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (78,'producto_1',13.2,5);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (79,'producto_1',13.2,5);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (80,'producto_2',2.9,5);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (81,'producto_2',2.9,5);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (82,'producto_2',2.9,5);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (83,'producto_3',4.9,5);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (84,'producto_3',4.9,5);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (85,'producto_3',4.9,5);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (86,'producto_3',4.9,5);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (87,'producto_3',4.9,5);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (88,'producto_4',11.9,5);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (89,'producto_5',17.5,5);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (90,'producto_5',17.5,5);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (91,'producto_5',17.5,5);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (92,'producto_5',17.5,5);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (93,'producto_5',17.5,5);")
	session.execute("INSERT INTO adquisiciones (id_obj, producto, importe, periodo) VALUES (94,'producto_5',17.5,5);")






def cargar_datos_ventas():
	#session.execute("DROP TABLE ventas;")
	session.execute("CREATE TABLE ventas (id_obj int PRIMARY KEY, producto text, importe float, periodo int);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (1,'producto_1',15.5,1);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (2,'producto_1',15.5,1);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (3,'producto_1',15.5,1);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (4,'producto_1',15.5,1);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (7,'producto_1',15.5,1);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (10,'producto_2',3.9,1);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (11,'producto_2',3.9,1);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (13,'producto_3',6.8,1);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (15,'producto_4',14.7,1);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (16,'producto_5',20.5,1);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (17,'producto_5',20.5,1);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (18,'producto_5',20.5,1);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (20,'producto_1',15.7,2);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (22,'producto_1',15.7,2);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (23,'producto_1',15.7,2);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (25,'producto_1',15.7,2);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (26,'producto_1',15.7,2);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (27,'producto_2',3.7,2);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (29,'producto_2',3.7,2);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (30,'producto_2',3.7,2);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (32,'producto_5',20.4,2);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (33,'producto_5',20.4,2);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (34,'producto_5',20.4,2);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (35,'producto_4',14.9,2);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (37,'producto_3',6.4,2);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (38,'producto_3',6.4,2);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (39,'producto_1',16.1,3);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (40,'producto_1',16.1,3);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (41,'producto_1',16.1,3);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (43,'producto_2',4.1,3);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (44,'producto_2',4.1,3);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (45,'producto_3',6.3,3);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (47,'producto_3',6.3,3);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (48,'producto_3',6.3,3);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (49,'producto_3',6.3,3);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (51,'producto_5',20.4,3);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (53,'producto_5',20.4,3);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (54,'producto_5',20.4,3);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (56,'producto_1',15.9,4);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (57,'producto_1',15.9,4);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (59,'producto_1',15.9,4);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (60,'producto_1',15.9,4);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (62,'producto_2',3.5,4);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (63,'producto_2',3.5,4);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (64,'producto_3',6.3,4);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (66,'producto_3',6.3,4);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (67,'producto_3',6.3,4);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (69,'producto_4',14.8,4);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (70,'producto_5',20.6,4);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (72,'producto_5',20.6,4);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (74,'producto_5',20.6,4);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (75,'producto_1',16.2,5);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (76,'producto_1',16.2,5);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (78,'producto_1',16.2,5);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (79,'producto_1',16.2,5);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (80,'producto_2',3.9,5);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (81,'producto_2',3.9,5);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (83,'producto_3',6.9,5);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (84,'producto_3',6.9,5);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (85,'producto_3',6.9,5);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (86,'producto_3',6.9,5);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (88,'producto_4',14.9,5);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (89,'producto_5',20.5,5);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (91,'producto_5',20.5,5);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (92,'producto_5',20.5,5);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (93,'producto_5',20.5,5);")
	session.execute("INSERT INTO ventas (id_obj, producto, importe, periodo) VALUES (94,'producto_5',20.5,5);")





def cargar_datos_reclamaciones():
	#session.execute("DROP TABLE reclamaciones;")
	session.execute("CREATE TABLE reclamaciones (id_obj int PRIMARY KEY, importe float, periodo int);")
	session.execute("INSERT INTO reclamaciones (id_obj, importe, periodo) VALUES (1, 4.3,1);")
	session.execute("INSERT INTO reclamaciones (id_obj, importe, periodo) VALUES (10, 0.2,1);")
	session.execute("INSERT INTO reclamaciones (id_obj, importe, periodo) VALUES (11, 0.2,1);")
	session.execute("INSERT INTO reclamaciones (id_obj, importe, periodo) VALUES (26, 2.2,2);")
	session.execute("INSERT INTO reclamaciones (id_obj, importe, periodo) VALUES (69, 2.1,4);")
	session.execute("INSERT INTO reclamaciones (id_obj, importe, periodo) VALUES (75, 2.3,5);")
	session.execute("INSERT INTO reclamaciones (id_obj, importe, periodo) VALUES (79, 2.3,5);")
	session.execute("INSERT INTO reclamaciones (id_obj, importe, periodo) VALUES (89, 3.4,5);")

	


cluster = Cluster()
print "Iniciando sesion..."
session = cluster.connect('ejemplo')
print "Revisando keyspaces en la DB..."
keyspaces = session.execute("SELECT * FROM system.schema_keyspaces;")
for k in keyspaces:
	print k.keyspace_name


#Ingresa los datos de adquisiciones a Cassandra
cargar_datos_adquisiciones()
#Ingresa los datos de ventas a Cassandra
cargar_datos_ventas()
#Ingresa los datos de reclamaciones a Cassandra
cargar_datos_reclamaciones()


